export const CHANGE_PROGRAM_DETAIL = "CHANGE_PROGRAM_DETAIL";
export const CHANGE_PROGRAM_COMMENT = "CHANGE_PROGRAM_COMMENT";
export const CHANGE_DJRADIO_PROGRAM_LIST = "CHANGE_DJRADIO_PROGRAM_LIST";
